import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ChatSideBar from 'components/home/ChatSideBar'
import { useState, useEffect } from 'react'
import ChatScreen from 'components/home/ChatScreen'
const inter = Inter({ subsets: ['latin'] })
import data from './../../data';
export default function Home() {
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [sideUsers, setsideUsers] = useState();
  const [allChat, setAllChat] = useState();
  const [user, setUser] = useState();
  const [receiver, setReceiver] = useState('user-2')
  const fetchSideUsers = async (id) => {
    const response = data.filter(item => item.id == id)[0];
    setUser({name:response.name, dp:response.dp, id:response.id});
    setAllChat(response.chats);
    setsideUsers(response.chats.map((item => item.id)));
  }
  useEffect(() => {
    fetchSideUsers('user-1');
  }, [])
  
  return (
    <>
      <Head>
        <title>Chatting Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="w-full h-[calc(100vh-1rem)] rounded-lg p-2 bg-gray-100 box-border">
          <div className="w-full flex h-[calc(100vh-1rem-1rem)] rounded bg-white box-border">
            <ChatSideBar setReceiver={setReceiver} user={user} setIsChatOpen={setIsChatOpen} sideUsers={sideUsers} allChat={allChat}/>
            <ChatScreen sender={user} recevier={receiver} allChat={allChat} />
          </div>
        </div>
      </main>
    </>
  )
}
